List userList = [
  {
    'displayName': 'Mario',
    'userID': 'pXe092W45sSw1AOPAb2bTMwbyHM2',
    'email':'itsmemario@gmail.com',
    'userName': '@SuperMario',
    'bio': "I'm-a gonna get you! - Mario Kart 7 and Mario Kart Wii",
    'imageUrl':
    'https://cdn.pocket-lint.com/r/s/1200x/assets/images/153339-games-news-does-mario-sunbathing-pic-mean-mario-sunshine-for-switch-is-near-image1-9zsg71zrml.jpg',
    'isVerified': true,
    'followers': 2,
    'followersList': ['USER_CODE2', 'USER_CODE3'],
    'following': 1,
    'followingList': ['USER_CODE4'],
    'coverImgUrl': 'https://static.13.cl/7/sites/default/files/esports/articulos/field-image/portadamariomovie.jpg',
  },
  {
    'displayName': 'Peach',
    'userID': 'RbMiUT8KOEfq77v5W8sFOvamTO42',
    'email':'peachdimario@gmail.com',
    'userName': '@PrincessPeach',
    'bio': "'Aww, sweet! I did it, yay!' From Mario Kart 7",
    'imageUrl':
    'https://play.nintendo.com/images/Masthead_Peach.17345b1513ac044897cfc243542899dce541e8dc.9afde10b.png',
    'isVerified': true,
    'followers': 0,
    'followersList': [],
    'following': 0,
    'followingList': [],
    'coverImgUrl': 'https://larepublica.pe/resizer/NiOI1KzSjGVDxqL2ILDv7Ct2EiA=/480x282/top/smart/cloudfront-us-east-1.images.arcpublishing.com/gruporepublica/VJKRS5C54ZCKVECZIHO3FSHOMY.jpg'
  },
  {
    'displayName': 'Bowser',
    'userID': 'RHqF6QMaAHQPvy5GPq6DJzzDyS33',
    'email':'bowserthekiller@gmail.com',
    'userName': '@KingBowserKoopa',
    'bio': "I'm the biggest, baddest brute around, and don't you forget it",
    'imageUrl':
    'https://i.pinimg.com/originals/07/02/53/0702539dbbe80e8cb200300984a9823a.png',
    'isVerified': false,
    'followers': 0,
    'followersList': [],
    'following': 0,
    'followingList': [],
    'coverImgUrl': 'https://as01.epimg.net/meristation/imagenes/2020/09/21/reportajes/1600724208_083151_1600874709_noticia_normal.jpg',
  },
  {
    'displayName': 'Crash',
    'userID': 'TZe7l4li4OhOSzI8OaXbhc5T7AN2',
    'userName': '@CrashBandicoot',
    'bio': "And wiping Crash Bandicoot off the face of the earth forever!",
    'imageUrl':
    'https://upload.wikimedia.org/wikipedia/en/1/16/Crash_Bandicoot.png',
    'isVerified': true,
    'followers': 0,
    'followersList': [],
    'following': 0,
    'followingList': [],
    'coverImgUrl': 'https://as01.epimg.net/meristation/imagenes/2021/03/14/noticias/1615731883_185671_1615731922_noticia_normal.jpg'
  },
  {
    'displayName': 'Neo',
    'userID': 'vTaFuFBIdzdUmPn9MrL54z7ltVG3',
    'userName': '@DoctorNeoCortex',
    'bio': "Burn baby burn! Like a disco inferno!",
    'imageUrl':
    'https://upload.wikimedia.org/wikipedia/en/8/87/IAT_Neo_Cortex.png',
    'isVerified': false,
    'followers': 0,
    'followersList': [],
    'following': 0,
    'followingList': [],
    'coverImgUrl': 'https://gcdn.lanetaneta.com/wp-content/uploads/2021/03/Como-vencer-a-Neo-Cortex-en-Crash-Bandicoot-4-ya-780x470.jpg',
  },
  {
    'displayName': 'kong',
    'userID': 'nCdvVujKdiNsrsMOOVVr0PaauK53',
    'userName': '@Donkeykong',
    'bio': "Banana slamma!!",
    'imageUrl':
    'http://static1.squarespace.com/static/5a448798dc2b4ae5dbdcb6d1/5a53e4e38165f574392d527e/5b6407b203ce6419bd18854e/1596353880021/whats+next+for+donkey+kong.jpg?format=1500w',
    'isVerified': true,
    'followers': 0,
    'followersList': [],
    'following': 0,
    'followingList': [],
    'coverImgUrl': 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/portals_3/H2x1_CharacterHub_DonkeyKong.jpg',
  },
  {
    'displayName': 'Kritter',
    'userID': 'BKSRknX9UgRIR2UrPiPvRImBbQm2',
    'userName': '@KritterTheKiller',
    'bio': "Just for fun",
    'imageUrl':
    'https://static.wikia.nocookie.net/villains/images/3/3e/Kritter_SSB_for_Wii_U.png/revision/latest?cb=20181119211905',
    'isVerified': false,
    'followers': 0,
    'followersList': [],
    'following': 0,
    'followingList': [],
    'coverImgUrl': 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/2a152e3c-fc2f-47d8-85a8-049fd02c8bde/ddqnm2c-241c825c-4e72-4893-a6c8-6b77319a1fc5.jpg/v1/fill/w_1192,h_670,q_70,strp/_mmd_model__kritter__klomp__and_kaboing_dl_by_sab64_ddqnm2c-pre.jpg',
  },
];
